/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author manji
 */
public class Dashborad extends javax.swing.JFrame {

    /**
     * Creates new form dashborad
     */
    public Dashborad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        subjectDetailbtn = new javax.swing.JButton();
        semesterDetail = new javax.swing.JButton();
        courseDetailbtn = new javax.swing.JButton();
        enrollCoursebtn = new javax.swing.JButton();
        registerbtn = new javax.swing.JButton();
        paymentbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(141, 199, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subjectDetailbtn.setBackground(new java.awt.Color(61, 196, 226));
        subjectDetailbtn.setText("Subject Detail");
        subjectDetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectDetailbtnActionPerformed(evt);
            }
        });
        jPanel2.add(subjectDetailbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 13, 227, 71));

        semesterDetail.setBackground(new java.awt.Color(61, 196, 226));
        semesterDetail.setText("Semester Detail");
        semesterDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterDetailActionPerformed(evt);
            }
        });
        jPanel2.add(semesterDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 227, 71));

        courseDetailbtn.setBackground(new java.awt.Color(61, 196, 226));
        courseDetailbtn.setText("Course Detail");
        courseDetailbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDetailbtnActionPerformed(evt);
            }
        });
        jPanel2.add(courseDetailbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 227, 71));

        enrollCoursebtn.setBackground(new java.awt.Color(61, 196, 226));
        enrollCoursebtn.setText("Enroll Courses");
        enrollCoursebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollCoursebtnActionPerformed(evt);
            }
        });
        jPanel2.add(enrollCoursebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 204, 227, 71));

        registerbtn.setBackground(new java.awt.Color(61, 196, 226));
        registerbtn.setText("Register");
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });
        jPanel2.add(registerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(631, 204, 227, 71));

        paymentbtn.setBackground(new java.awt.Color(61, 196, 226));
        paymentbtn.setText("Payment");
        paymentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbtnActionPerformed(evt);
            }
        });
        jPanel2.add(paymentbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 227, 71));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 197, 870, 350));

        jPanel3.setBackground(new java.awt.Color(25, 88, 157));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 870, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enrollCoursebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollCoursebtnActionPerformed
            SelectDegreeProgramme1 selectDegreeProgramme1=new SelectDegreeProgramme1();
            selectDegreeProgramme1.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_enrollCoursebtnActionPerformed

    private void semesterDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterDetailActionPerformed
            Semester semester=new Semester();
            semester.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_semesterDetailActionPerformed

    private void subjectDetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectDetailbtnActionPerformed
            Subject_view subject_view=new Subject_view();
            subject_view.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_subjectDetailbtnActionPerformed

    private void courseDetailbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseDetailbtnActionPerformed
        Course_view course_view=new Course_view();
        course_view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_courseDetailbtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        Register_users register_users=new Register_users();
        register_users.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerbtnActionPerformed

    private void paymentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbtnActionPerformed
        Payment payment=new Payment();
        payment.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_paymentbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashborad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashborad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton courseDetailbtn;
    private javax.swing.JButton enrollCoursebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton paymentbtn;
    private javax.swing.JButton registerbtn;
    private javax.swing.JButton semesterDetail;
    private javax.swing.JButton subjectDetailbtn;
    // End of variables declaration//GEN-END:variables
}
