/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.lectureController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.LectureModel;

/**
 *
 * @author manji
 */
public class LectureReg extends javax.swing.JFrame {

    /**
     * Creates new form studentReg
     */
    public LectureReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nictxt = new javax.swing.JTextField();
        userNametxt = new javax.swing.JTextField();
        regNotxt = new javax.swing.JTextField();
        indexNotxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        mobiletxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        editbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nameWithInitialstxt1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        searchbtn1 = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 181, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(141, 199, 63));

        jPanel7.setBackground(new java.awt.Color(141, 199, 63));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lecture Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("User Name");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Reg No");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Index No");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NIC");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Password");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        jPanel7.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));
        jPanel7.add(userNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));
        jPanel7.add(regNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));
        jPanel7.add(indexNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));
        jPanel7.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));
        jPanel7.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        addresstxt.setColumns(20);
        addresstxt.setRows(5);
        jScrollPane1.setViewportView(addresstxt);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 170, -1));

        editbtn.setBackground(new java.awt.Color(49, 144, 176));
        editbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel7.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 400, 100, -1));

        cancelbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel7.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Name with Initials");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel7.add(nameWithInitialstxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 100, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Address");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));
        jPanel7.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 100, -1));

        searchbtn1.setBackground(new java.awt.Color(49, 144, 176));
        searchbtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn1.setText("Search");
        searchbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtn1ActionPerformed(evt);
            }
        });
        jPanel7.add(searchbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 100, -1));

        deletebtn1.setBackground(new java.awt.Color(49, 144, 176));
        deletebtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn1.setText("Delete");
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });
        jPanel7.add(deletebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 100, -1));

        submitbtn.setBackground(new java.awt.Color(49, 144, 176));
        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel7.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 100, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 440));

        jPanel5.setBackground(new java.awt.Color(25, 88, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel10.setText("jLabel1");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 216, 122));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 840, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
            this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
      Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel10MouseClicked

            //(String nameWithIntials,String userName,String regNo,String indexNo,String email,String mobile,String nic,String address,String password){

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        String nameWithIntials=nameWithInitialstxt1.getText();
        String userName=userNametxt.getText();
        String regNo=regNotxt.getText();
        String indexNo=indexNotxt.getText();
        String email=emailtxt.getText();
        String mobile=mobiletxt.getText();
        String nic=nictxt.getText();
        String address=addresstxt.getText();
        String password=passwordtxt.getText();
        LectureModel lecture=new LectureModel(nameWithIntials,userName,regNo,indexNo,email,mobile,nic,address,password);
        System.out.println(nameWithIntials+userName+regNo+indexNo+email+mobile+nic+address+password);
        try{
            int res=lectureController.editLecture(lecture);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Added Success");
            } 
            else{
                JOptionPane.showMessageDialog(this, "Can;t add data");

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editbtnActionPerformed
   
    private void searchbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtn1ActionPerformed
        String regNo=regNotxt.getText();
        try{
            LectureModel lectureModel=lectureController.searchLecture(regNo);
            if(lectureModel !=null){
                nameWithInitialstxt1.setText(lectureModel.getNameWithIntials());
                userNametxt.setText(lectureModel.getUserName());
                regNotxt.setText(lectureModel.getRegNo());
                indexNotxt.setText(lectureModel.getIndexNo());
                emailtxt.setText(lectureModel.getEmail());
                mobiletxt.setText(lectureModel.getMobile());
                nictxt.setText(lectureModel.getNic());
                addresstxt.setText(lectureModel.getAddress());
                
                
                
 //(String nameWithIntials,String userName,String regNo,String indexNo,String email,String mobile,String nic,String address,String password){

            }
            else {
                JOptionPane.showMessageDialog(this, "No Such Course ");
            }  
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbtn1ActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed
        String id=regNotxt.getText();
         try {
            int res = lectureController.deleteLecture(id);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Delete Success ");
            } else {
                JOptionPane.showMessageDialog(this, "Delete Fail ");
            }    
         }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_deletebtn1ActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
         String nameWithIntials=nameWithInitialstxt1.getText();
        String userName=userNametxt.getText();
        String regNo=regNotxt.getText();
        String indexNo=indexNotxt.getText();
        String email=emailtxt.getText();
        String mobile=mobiletxt.getText();
        String nic=nictxt.getText();
        String address=addresstxt.getText();
        String password=passwordtxt.getText();
        LectureModel lecture=new LectureModel(nameWithIntials,userName,regNo,indexNo,email,mobile,nic,address,password);
        
         try{
             int res = lectureController.addLecture(lecture);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }  
            else{
                JOptionPane.showMessageDialog(this, "Can't edit");
            }} catch (ClassNotFoundException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LectureReg.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LectureReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LectureReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LectureReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LectureReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LectureReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField indexNotxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nameWithInitialstxt1;
    private javax.swing.JTextField nictxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField regNotxt;
    private javax.swing.JButton searchbtn1;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField userNametxt;
    // End of variables declaration//GEN-END:variables
}
