/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PostgraduateController;
import controller.UndergraduateStudentController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.PostgraduateStudentModel;
import model.UndergraduateStudentModel;
import other.IDGenerator;

/**
 *
 * @author manji
 */
public class PostgraduateStudent extends javax.swing.JFrame {

    /**
     * Creates new form studentReg
     */
    public PostgraduateStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nameWithIntialstxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        userNametxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        regNotxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        indexNotxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mobiletxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nictxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        insitutetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qualificationTypetxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        courseIdtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        datetebtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        addmissiontxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel26 = new javax.swing.JLabel();
        facultyId = new javax.swing.JLabel();
        qualificationtxt1 = new javax.swing.JTextField();
        facultyIdtxt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 181, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(141, 199, 63));

        jPanel7.setBackground(new java.awt.Color(141, 199, 63));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Postgraduate Student Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(141, 199, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Name with Initials");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 47, -1, 30));
        jPanel2.add(nameWithIntialstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("User Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanel2.add(userNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Reg No");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel2.add(regNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Index No");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel2.add(indexNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Email");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Mobile");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        jPanel2.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("NIC");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));
        jPanel2.add(nictxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Addmission date");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        addresstxt.setColumns(20);
        addresstxt.setRows(5);
        jScrollPane2.setViewportView(addresstxt);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Insitute");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, 30));
        jPanel2.add(insitutetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Qualification Type");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 30));
        jPanel2.add(qualificationTypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 100, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Course Id");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, 30));
        jPanel2.add(courseIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 100, -1));

        searchbtn.setBackground(new java.awt.Color(49, 144, 176));
        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel2.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 50, 80, -1));

        editbtn.setBackground(new java.awt.Color(49, 144, 176));
        editbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel2.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 80, -1));

        datetebtn.setBackground(new java.awt.Color(49, 144, 176));
        datetebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datetebtn.setText("Delete");
        datetebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetebtnActionPerformed(evt);
            }
        });
        jPanel2.add(datetebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 80, -1));

        submitbtn.setBackground(new java.awt.Color(49, 144, 176));
        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel2.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 90, -1));

        cancelbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        jPanel2.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 80, -1));

        backbtn.setBackground(new java.awt.Color(49, 144, 176));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setText("Back");
        jPanel2.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, 80, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Address");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        addmissiontxt.setText("2018-05-22");
        jPanel2.add(addmissiontxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 90, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Qualification");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 30));
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Password");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, 30));

        facultyId.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        facultyId.setText("Faculty Id");
        jPanel2.add(facultyId, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, 30));
        jPanel2.add(qualificationtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, -1));
        jPanel2.add(facultyIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 100, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 845, 490));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 440));

        jPanel5.setBackground(new java.awt.Color(25, 88, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel10.setText("jLabel1");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 216, 122));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 840, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel10MouseClicked

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
       
        String nameWithInitials=nameWithIntialstxt.getText();
        String userName=userNametxt.getText();
        String regNo=regNotxt.getText();
        String indexNo=indexNotxt.getText();
        String email=emailtxt.getText();
        String mobile=mobiletxt.getText();
        String nic=nictxt.getText();
        String address=addresstxt.getText();
        String addmissionDate=addmissiontxt.getText();
        String institute=insitutetxt.getText();
        String qualificationType=qualificationTypetxt.getText();
        String qualification=qualificationtxt1.getText();
        String faculty=facultyIdtxt.getText();
        String courseId=courseIdtxt.getText();
        String password=passwordtxt.getText();
        
       PostgraduateStudentModel postgraduateStudentModel=new PostgraduateStudentModel(nameWithInitials, userName, regNo, indexNo, addmissionDate, email, mobile, nic, address, institute, qualificationType, qualification, faculty, courseId, password);
       
       //int res;
       int res = 0;
        try {
            res = PostgraduateController.addPostStudent(postgraduateStudentModel);
            if(res>0){
           JOptionPane.showMessageDialog(this, "Added Success");
       }
        } 
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
       
    }//GEN-LAST:event_submitbtnActionPerformed

    private void datetebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetebtnActionPerformed
      
      String id=regNotxt.getText();
        try {
            int res=PostgraduateController.deletePostStudent(id);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Delete Success ");
            } else {
                JOptionPane.showMessageDialog(this, "Delete Fail ");
            } 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
      
      
    }//GEN-LAST:event_datetebtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
       
       String nameWithInitials=nameWithIntialstxt.getText();
        String userName=userNametxt.getText();
        String regNo=regNotxt.getText();
        String indexNo=indexNotxt.getText();
        String email=emailtxt.getText();
        String mobile=mobiletxt.getText();
        String nic=nictxt.getText();
        String address=addresstxt.getText();
        String addmissionDate=addmissiontxt.getText();
        String institute=insitutetxt.getText();
        String qualificationType=qualificationTypetxt.getText();
        String qualification=qualificationtxt1.getText();
        String faculty=facultyIdtxt.getText();
        String courseId=courseIdtxt.getText();
        String password=passwordtxt.getText();
        
       PostgraduateStudentModel postgraduateStudentModel=new PostgraduateStudentModel(nameWithInitials, userName, regNo, indexNo, addmissionDate, email, mobile, nic, address, institute, qualificationType, qualification, faculty, courseId, password);
       try{
           int res=PostgraduateController.editPostStudent(postgraduateStudentModel);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Update Success");
            }
            else{
               JOptionPane.showMessageDialog(this, "Update Fail"); 
            }
           
       } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
       
       
       String id=regNotxt.getText();
       try{
       PostgraduateStudentModel postgraduateStudentModel=PostgraduateController.searchPostStudent(id);
       if (postgraduateStudentModel != null) {
                nameWithIntialstxt.setText(postgraduateStudentModel.getNameWithIntials());
                userNametxt.setText(postgraduateStudentModel.getUserName());
                regNotxt.setText(postgraduateStudentModel.getRegNo());
                indexNotxt.setText(postgraduateStudentModel.getIndexNo());
                emailtxt.setText(postgraduateStudentModel.getEmail());
                mobiletxt.setText(postgraduateStudentModel.getMobile());
                nictxt.setText(postgraduateStudentModel.getNic());
                addresstxt.setText(postgraduateStudentModel.getAddress());
                addmissiontxt.setText(postgraduateStudentModel.getAdmission());
                insitutetxt.setText(postgraduateStudentModel.getInsitute());
                qualificationTypetxt.setText(postgraduateStudentModel.getQualificationType());
                qualificationtxt1.setText(postgraduateStudentModel.getQualification());
                facultyIdtxt.setText(postgraduateStudentModel.getFacultyId());
                courseIdtxt.setText(postgraduateStudentModel.getCourseId());
                
                
                
               
            } else {
                JOptionPane.showMessageDialog(this, "No Such Student ");
            }
       } catch (ClassNotFoundException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(PostgraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_searchbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgraduateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgraduateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgraduateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgraduateStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgraduateStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addmissiontxt;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JButton backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField courseIdtxt;
    private javax.swing.JButton datetebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel facultyId;
    private javax.swing.JTextField facultyIdtxt;
    private javax.swing.JTextField indexNotxt;
    private javax.swing.JTextField insitutetxt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nameWithIntialstxt;
    private javax.swing.JTextField nictxt;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JTextField qualificationTypetxt;
    private javax.swing.JTextField qualificationtxt1;
    private javax.swing.JTextField regNotxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField userNametxt;
    // End of variables declaration//GEN-END:variables

   /* private void newS_id(){
        String newS_id=IDGenerator.getNewId(tableName, columnName, prefix)
    }*/
}
