/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author manji
 */
public class School_of_Business extends javax.swing.JFrame {

    /**
     * Creates new form dashborad
     */
    public School_of_Business() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bscBusinessManagementbtn = new javax.swing.JButton();
        bscBusinessMangementlmbtn = new javax.swing.JButton();
        bscBusinessimbtn = new javax.swing.JButton();
        bscBusinessManagementimsbtn = new javax.swing.JButton();
        baInBusinessCommunicationbtn = new javax.swing.JButton();
        bachelorOfInteriorbtn = new javax.swing.JButton();
        bmInAccount = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        postgarduatedipInHumanbtn = new javax.swing.JButton();
        postgraduateDipInBusbtn = new javax.swing.JButton();
        MAsterOfBusinessAdminbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(141, 199, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bscBusinessManagementbtn.setBackground(new java.awt.Color(61, 196, 226));
        bscBusinessManagementbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bscBusinessManagementbtn.setText("BSc in Business Management (Human Resource Management) (Special)");
        bscBusinessManagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscBusinessManagementbtnActionPerformed(evt);
            }
        });
        jPanel2.add(bscBusinessManagementbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 500, -1));

        bscBusinessMangementlmbtn.setBackground(new java.awt.Color(61, 196, 226));
        bscBusinessMangementlmbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bscBusinessMangementlmbtn.setText("BSc in Business Management (Logistics Management) (Special)");
        bscBusinessMangementlmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscBusinessMangementlmbtnActionPerformed(evt);
            }
        });
        jPanel2.add(bscBusinessMangementlmbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 500, -1));

        bscBusinessimbtn.setBackground(new java.awt.Color(61, 196, 226));
        bscBusinessimbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bscBusinessimbtn.setText("BSc in Business Management (Project Management) (Special)");
        bscBusinessimbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscBusinessimbtnActionPerformed(evt);
            }
        });
        jPanel2.add(bscBusinessimbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 500, -1));

        bscBusinessManagementimsbtn.setBackground(new java.awt.Color(61, 196, 226));
        bscBusinessManagementimsbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bscBusinessManagementimsbtn.setText("BSc in Business Management (Industrial Management) (Special)");
        bscBusinessManagementimsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bscBusinessManagementimsbtnActionPerformed(evt);
            }
        });
        jPanel2.add(bscBusinessManagementimsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 500, -1));

        baInBusinessCommunicationbtn.setBackground(new java.awt.Color(61, 196, 226));
        baInBusinessCommunicationbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        baInBusinessCommunicationbtn.setText("BA in Business Communication ");
        baInBusinessCommunicationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baInBusinessCommunicationbtnActionPerformed(evt);
            }
        });
        jPanel2.add(baInBusinessCommunicationbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 500, -1));

        bachelorOfInteriorbtn.setBackground(new java.awt.Color(61, 196, 226));
        bachelorOfInteriorbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bachelorOfInteriorbtn.setText("Bachelor of Interior Design");
        bachelorOfInteriorbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bachelorOfInteriorbtnActionPerformed(evt);
            }
        });
        jPanel2.add(bachelorOfInteriorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 500, -1));

        bmInAccount.setBackground(new java.awt.Color(61, 196, 226));
        bmInAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bmInAccount.setText("BM in Accounting & Finance (Special)");
        bmInAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmInAccountActionPerformed(evt);
            }
        });
        jPanel2.add(bmInAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 500, -1));

        jButton8.setText("Back");
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 550, -1, -1));

        jPanel5.setBackground(new java.awt.Color(141, 199, 63));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Undergraduate Degree Businees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 860, 330));

        jPanel6.setBackground(new java.awt.Color(141, 199, 63));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Postgraduate Degree in Business", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        postgarduatedipInHumanbtn.setBackground(new java.awt.Color(61, 196, 226));
        postgarduatedipInHumanbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        postgarduatedipInHumanbtn.setText("Postgraduate Diploma in Human Resource Management");
        postgarduatedipInHumanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgarduatedipInHumanbtnActionPerformed(evt);
            }
        });
        jPanel6.add(postgarduatedipInHumanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 500, -1));

        postgraduateDipInBusbtn.setBackground(new java.awt.Color(61, 196, 226));
        postgraduateDipInBusbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        postgraduateDipInBusbtn.setText("Postgraduate Diploma in Business Management");
        postgraduateDipInBusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postgraduateDipInBusbtnActionPerformed(evt);
            }
        });
        jPanel6.add(postgraduateDipInBusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 500, -1));

        MAsterOfBusinessAdminbtn.setBackground(new java.awt.Color(61, 196, 226));
        MAsterOfBusinessAdminbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MAsterOfBusinessAdminbtn.setText("Master of Business Administration");
        MAsterOfBusinessAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAsterOfBusinessAdminbtnActionPerformed(evt);
            }
        });
        jPanel6.add(MAsterOfBusinessAdminbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 500, -1));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 860, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, 900, 580));

        jPanel3.setBackground(new java.awt.Color(25, 88, 157));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 900, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bscBusinessManagementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscBusinessManagementbtnActionPerformed
       UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
       
    }//GEN-LAST:event_bscBusinessManagementbtnActionPerformed

    private void bscBusinessMangementlmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscBusinessMangementlmbtnActionPerformed
        UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bscBusinessMangementlmbtnActionPerformed

    private void postgarduatedipInHumanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgarduatedipInHumanbtnActionPerformed
       PostgraduateStudent postGraduateStudent=new PostgraduateStudent();
       postGraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_postgarduatedipInHumanbtnActionPerformed

    private void postgraduateDipInBusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postgraduateDipInBusbtnActionPerformed
      PostgraduateStudent postGraduateStudent=new PostgraduateStudent();
       postGraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_postgraduateDipInBusbtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bscBusinessimbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscBusinessimbtnActionPerformed
      UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bscBusinessimbtnActionPerformed

    private void bscBusinessManagementimsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bscBusinessManagementimsbtnActionPerformed
      UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bscBusinessManagementimsbtnActionPerformed

    private void baInBusinessCommunicationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baInBusinessCommunicationbtnActionPerformed
        UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_baInBusinessCommunicationbtnActionPerformed

    private void bmInAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmInAccountActionPerformed
       UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bmInAccountActionPerformed

    private void bachelorOfInteriorbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bachelorOfInteriorbtnActionPerformed
       UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
       undergraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_bachelorOfInteriorbtnActionPerformed

    private void MAsterOfBusinessAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAsterOfBusinessAdminbtnActionPerformed
        PostgraduateStudent postGraduateStudent=new PostgraduateStudent();
       postGraduateStudent.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_MAsterOfBusinessAdminbtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(School_of_Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(School_of_Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(School_of_Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(School_of_Business.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new School_of_Business().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MAsterOfBusinessAdminbtn;
    private javax.swing.JButton baInBusinessCommunicationbtn;
    private javax.swing.JButton bachelorOfInteriorbtn;
    private javax.swing.JButton bmInAccount;
    private javax.swing.JButton bscBusinessManagementbtn;
    private javax.swing.JButton bscBusinessManagementimsbtn;
    private javax.swing.JButton bscBusinessMangementlmbtn;
    private javax.swing.JButton bscBusinessimbtn;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JButton postgarduatedipInHumanbtn;
    private javax.swing.JButton postgraduateDipInBusbtn;
    // End of variables declaration//GEN-END:variables
}
