/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author manji
 */
public class SelectDegreeProgramme1 extends javax.swing.JFrame {

    /**
     * Creates new form dashborad
     */
    public SelectDegreeProgramme1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        School_of_Businessbtn = new javax.swing.JButton();
        School_of_Computingbtn = new javax.swing.JButton();
        School_of_Engineeringbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        School_of_Businesspostbtn = new javax.swing.JButton();
        School_of_Computingpostbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(58, 181, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(141, 199, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select a degree program");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 500, -1));

        jButton1.setBackground(new java.awt.Color(61, 196, 226));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Foundation Programme for Bachelors Degree");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 500, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Undergraduate Programmes");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 500, -1));

        School_of_Businessbtn.setBackground(new java.awt.Color(61, 196, 226));
        School_of_Businessbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        School_of_Businessbtn.setText("School of Business");
        School_of_Businessbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_of_BusinessbtnActionPerformed(evt);
            }
        });
        jPanel2.add(School_of_Businessbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 500, -1));

        School_of_Computingbtn.setBackground(new java.awt.Color(61, 196, 226));
        School_of_Computingbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        School_of_Computingbtn.setText("School of Computing");
        School_of_Computingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_of_ComputingbtnActionPerformed(evt);
            }
        });
        jPanel2.add(School_of_Computingbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 500, -1));

        School_of_Engineeringbtn.setBackground(new java.awt.Color(61, 196, 226));
        School_of_Engineeringbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        School_of_Engineeringbtn.setText("School of Engineering");
        School_of_Engineeringbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_of_EngineeringbtnActionPerformed(evt);
            }
        });
        jPanel2.add(School_of_Engineeringbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 500, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Postgraduate Programmes");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 500, -1));

        School_of_Businesspostbtn.setBackground(new java.awt.Color(61, 196, 226));
        School_of_Businesspostbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        School_of_Businesspostbtn.setText("School of Business");
        School_of_Businesspostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_of_BusinesspostbtnActionPerformed(evt);
            }
        });
        jPanel2.add(School_of_Businesspostbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 500, -1));

        School_of_Computingpostbtn.setBackground(new java.awt.Color(61, 196, 226));
        School_of_Computingpostbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        School_of_Computingpostbtn.setText("School of Computing");
        School_of_Computingpostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                School_of_ComputingpostbtnActionPerformed(evt);
            }
        });
        jPanel2.add(School_of_Computingpostbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 500, -1));

        backbtn.setBackground(new java.awt.Color(49, 144, 176));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel2.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 147, 900, 580));

        jPanel3.setBackground(new java.awt.Color(25, 88, 157));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 900, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 919, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            UndergraduateStudent undergraduateStudent=new UndergraduateStudent();
            undergraduateStudent.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void School_of_BusinessbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_of_BusinessbtnActionPerformed
            
            School_of_Business school_of_Business=new School_of_Business();
            school_of_Business.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_School_of_BusinessbtnActionPerformed

    private void School_of_ComputingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_of_ComputingbtnActionPerformed
        School_of_Computing school_of_Computing=new School_of_Computing();
        school_of_Computing.setVisible(true);
        this.dispose();
        
                
    }//GEN-LAST:event_School_of_ComputingbtnActionPerformed

    private void School_of_EngineeringbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_of_EngineeringbtnActionPerformed
       School_of_Engineering school_of_Engineering=new School_of_Engineering();
       school_of_Engineering.setVisible(true);
       this.dispose();
               
    }//GEN-LAST:event_School_of_EngineeringbtnActionPerformed

    private void School_of_BusinesspostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_of_BusinesspostbtnActionPerformed
              School_of_Business school_of_Business=new School_of_Business();
            school_of_Business.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_School_of_BusinesspostbtnActionPerformed

    private void School_of_ComputingpostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_School_of_ComputingpostbtnActionPerformed
       School_of_Computing school_of_Computing=new School_of_Computing();
        school_of_Computing.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_School_of_ComputingpostbtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectDegreeProgramme1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectDegreeProgramme1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectDegreeProgramme1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectDegreeProgramme1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectDegreeProgramme1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton School_of_Businessbtn;
    private javax.swing.JButton School_of_Businesspostbtn;
    private javax.swing.JButton School_of_Computingbtn;
    private javax.swing.JButton School_of_Computingpostbtn;
    private javax.swing.JButton School_of_Engineeringbtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
