/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SemesterController;
import java.sql.Date;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.SemesterModel;

/**
 *
 * @author manji
 */
public class Semester extends javax.swing.JFrame {

    /**
     * Creates new form studentReg
     */
    public Semester() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        courseNametxt = new javax.swing.JTextField();
        courseIdtxt = new javax.swing.JTextField();
        semesterIdtxt = new javax.swing.JTextField();
        semeste = new javax.swing.JLabel();
        semesterFeestxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        endDatetxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        startDatetxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        submitbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        datetebtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 181, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(141, 199, 63));

        jPanel7.setBackground(new java.awt.Color(141, 199, 63));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semester Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Course Name");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Course Id");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Semester Id");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));
        jPanel7.add(courseNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));
        jPanel7.add(courseIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));
        jPanel7.add(semesterIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        semeste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        semeste.setText("Semester Fees");
        jPanel7.add(semeste, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel7.add(semesterFeestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("End date");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, -1));

        endDatetxt.setText("yyyy-MM-dd");
        jPanel7.add(endDatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Start date");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, -1));

        startDatetxt.setText("yyyy-MM-dd");
        jPanel7.add(startDatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel7.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        submitbtn.setBackground(new java.awt.Color(49, 144, 176));
        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel7.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, -1));

        cancelbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel7.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        backbtn.setBackground(new java.awt.Color(49, 144, 176));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel7.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel7.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, -1, -1));

        datetebtn.setText("Delete");
        datetebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datetebtnActionPerformed(evt);
            }
        });
        jPanel7.add(datetebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 440));

        jPanel5.setBackground(new java.awt.Color(25, 88, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 216, 122));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 840, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed

        String id=semesterIdtxt.getText();

        try{
            SemesterModel semesterModel = SemesterController.searchSemester(id);
            if (semesterModel != null) {
                courseNametxt.setText(semesterModel.getCourseName());
                courseIdtxt.setText(semesterModel.getCourseId());
                semesterIdtxt.setText(semesterModel.getSemesterId());
                semesterFeestxt.setText(Double.toString(semesterModel.getSemesterFees()));
                startDatetxt.setText(semesterModel.getStart());
                endDatetxt.setText(semesterModel.getEnd());

            } else {
                JOptionPane.showMessageDialog(this, "No Such Course ");
            }        }
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No Driver found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            }

    }//GEN-LAST:event_searchbtnActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed

        String courseName=courseNametxt.getText();
        String courseId=courseIdtxt.getText();
        String semesterId=semesterIdtxt.getText();
        double semesterFees = Double.parseDouble(semesterFeestxt.getText());
        String start=startDatetxt.getText();
        String end=endDatetxt.getText();
        
        SemesterModel semesterModel=new SemesterModel(courseName, courseId, semesterId, semesterFees, start, end);

        //System.out.println(courseName.length());
        try{
            int res = SemesterController.addSemester(semesterModel);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Added Success");
            }        }
            catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "No Driver found");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());

            }

    }//GEN-LAST:event_submitbtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        String courseName=courseNametxt.getText();
        String courseId=courseIdtxt.getText();
        String semesterId=semesterIdtxt.getText();
        double semesterFees = Double.parseDouble(semesterFeestxt.getText());
        String start=startDatetxt.getText();
        String end=endDatetxt.getText();

        SemesterModel semesterModel=new SemesterModel(courseName,courseId,semesterId,semesterFees,start,end);

        //System.out.println("IN course edit");
        try {
            int res=SemesterController.editSemester(semesterModel);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Update Success");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Semester.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    }//GEN-LAST:event_editbtnActionPerformed

    private void datetebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datetebtnActionPerformed
        String id=semesterIdtxt.getText();
        try {
            int res = SemesterController.deleteSemester(id);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Delete Success ");
            } else {
                JOptionPane.showMessageDialog(this, "Delete Fail ");
            }
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }

    }//GEN-LAST:event_datetebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Semester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Semester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JTextField courseIdtxt;
    private javax.swing.JTextField courseNametxt;
    private javax.swing.JButton datetebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField endDatetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton searchbtn;
    private javax.swing.JLabel semeste;
    private javax.swing.JTextField semesterFeestxt;
    private javax.swing.JTextField semesterIdtxt;
    private javax.swing.JTextField startDatetxt;
    private javax.swing.JButton submitbtn;
    // End of variables declaration//GEN-END:variables
}
