/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PostgraduateController;
import controller.UndergraduateStudentController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.PostgraduateStudentModel;
import model.UndergraduateStudentModel;
import other.IDGenerator;

/**
 *
 * @author manji
 */
public class StudentReg extends javax.swing.JFrame {

    /**
     * Creates new form studentReg
     */
    public StudentReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameWithInitials1txt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        userName1txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        regNo1txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        indexNo1txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        email1txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        mobile1txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        admissionDate1txt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address1txt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        subGrade3txt = new javax.swing.JTextField();
        subName2txt = new javax.swing.JTextField();
        zScoretxt = new javax.swing.JTextField();
        engGradetxt = new javax.swing.JTextField();
        inslandRanktxt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        subName1txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        subName3txt = new javax.swing.JTextField();
        subGrade2txt = new javax.swing.JTextField();
        subGrade1txt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        underSubmitbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        nic1txt1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        facultyIdtxt1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        courseIdtxt1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        passwordtxt1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        nameWithInitialstxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        userNametxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        regNotxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        indexNotxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        mobiletxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        admissionDatetxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addresstxt = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        insitutetxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        qualificationTypetxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        qualificationtxt = new javax.swing.JTextField();
        postSubmitbtnpostbtn = new javax.swing.JButton();
        cancelpostbtn = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        nictxt1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        facultyIdtxt = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        courseIdtxt = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 181, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(141, 199, 63));

        jPanel7.setBackground(new java.awt.Color(141, 199, 63));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setForeground(new java.awt.Color(25, 88, 157));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(141, 199, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name with Initials");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 47, -1, 30));
        jPanel1.add(nameWithInitials1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("User Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanel1.add(userName1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Reg No");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel1.add(regNo1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Index No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel1.add(indexNo1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        jPanel1.add(email1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Mobile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        jPanel1.add(mobile1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("NIC");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));
        jPanel1.add(admissionDate1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Admission Date");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        address1txt.setColumns(20);
        address1txt.setRows(5);
        jScrollPane1.setViewportView(address1txt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));

        jButton1.setBackground(new java.awt.Color(49, 144, 176));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Next");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jButton2.setBackground(new java.awt.Color(49, 144, 176));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Subject Grade");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 30));
        jPanel1.add(subGrade3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 100, -1));
        jPanel1.add(subName2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 100, -1));
        jPanel1.add(zScoretxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 100, -1));
        jPanel1.add(engGradetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 100, -1));
        jPanel1.add(inslandRanktxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 100, -1));

        jButton5.setText("Submit");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, -1, -1));
        jPanel1.add(subName1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 100, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("General English");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 30));
        jPanel1.add(subName3txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 100, -1));
        jPanel1.add(subGrade2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 100, -1));
        jPanel1.add(subGrade1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 100, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Iland Rank");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, -1, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Z-Score");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 22, 30, 310));

        underSubmitbtn.setBackground(new java.awt.Color(49, 144, 176));
        underSubmitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        underSubmitbtn.setText("Submit");
        underSubmitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underSubmitbtnActionPerformed(evt);
            }
        });
        jPanel1.add(underSubmitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 100, -1));

        cancelbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel1.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 100, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Subject Name");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, -1, 30));
        jPanel1.add(nic1txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Address");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Faculty Id");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, 30));
        jPanel1.add(facultyIdtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 100, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Course Id");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, -1, 30));
        jPanel1.add(courseIdtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 100, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Password");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, 30));
        jPanel1.add(passwordtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 100, -1));

        jTabbedPane1.addTab("Undergaduate", jPanel1);

        jPanel2.setBackground(new java.awt.Color(141, 199, 63));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Name with Initials");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 47, -1, 30));
        jPanel2.add(nameWithInitialstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 100, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("User Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        jPanel2.add(userNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Reg No");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        jPanel2.add(regNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Index No");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));
        jPanel2.add(indexNotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 100, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Email");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));
        jPanel2.add(emailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 100, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Mobile");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));
        jPanel2.add(mobiletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 100, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("NIC");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));
        jPanel2.add(admissionDatetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 100, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Admession Date");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        addresstxt.setColumns(20);
        addresstxt.setRows(5);
        jScrollPane2.setViewportView(addresstxt);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 170, -1));

        jButton3.setBackground(new java.awt.Color(49, 144, 176));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Next");
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jButton4.setBackground(new java.awt.Color(49, 144, 176));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Cancel");
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 160, 390));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Insitute");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, 30));
        jPanel2.add(insitutetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Qualification Type");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, 30));
        jPanel2.add(qualificationTypetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 100, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Qualification");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, 30));
        jPanel2.add(qualificationtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 100, -1));

        postSubmitbtnpostbtn.setBackground(new java.awt.Color(49, 144, 176));
        postSubmitbtnpostbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        postSubmitbtnpostbtn.setText("Submit");
        postSubmitbtnpostbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postSubmitbtnpostbtnActionPerformed(evt);
            }
        });
        jPanel2.add(postSubmitbtnpostbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 100, -1));

        cancelpostbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelpostbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelpostbtn.setText("Cancel");
        jPanel2.add(cancelpostbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 100, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Address");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));
        jPanel2.add(nictxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 100, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Faculty Id");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, 30));
        jPanel2.add(facultyIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 100, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Course Id");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, 30));
        jPanel2.add(courseIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 100, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Password");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, 30));
        jPanel2.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 100, -1));

        jTabbedPane1.addTab("Postgraduate", jPanel2);

        jPanel7.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 830, 430));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 440));

        jPanel5.setBackground(new java.awt.Color(25, 88, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 840, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
            this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       Dashborad dashborad=new Dashborad();
            dashborad.setVisible(true);
            this.dispose();  
    }//GEN-LAST:event_jLabel1MouseClicked

    private void underSubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underSubmitbtnActionPerformed
        String nameWithIntials=nameWithInitials1txt.getText();
        String userName=userName1txt.getText();
        String regNo=regNo1txt.getText();
        String indexNo=indexNo1txt.getText();
        String admission=admissionDate1txt.getText();
        String email=email1txt.getText();
        String mobile=mobile1txt.getText();
        String nic=admissionDate1txt.getText();
        String address=address1txt.getText();
        String subName1=subName1txt.getText();
        String subGrade1=subGrade1txt.getText();
        String subName2=subName2txt.getText();
        String subName3=subGrade3txt.getText();
        String engGrade=engGradetxt.getText();
        String isislandRank=inslandRanktxt.getText();
        String zScore=zScoretxt.getText();
        String facultyId=facultyIdtxt.getText();
        String courseId=courseIdtxt.getText();
        String password=passwordtxt.getText();
        UndergraduateStudentModel undergraduateStudentModel=new UndergraduateStudentModel(nameWithIntials, userName, regNo, indexNo, admission, email, mobile, nic, address, subName1, subGrade1, subName2, subGrade1, subName3, subGrade1, engGrade, isislandRank, zScore, facultyId, courseId, password);

                int res;
        try {
            res = UndergraduateStudentController.addUnderStudent(undergraduateStudentModel);
            if (res > 0) {
            JOptionPane.showMessageDialog(this, "Added Success");
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(UndergraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
           // Logger.getLogger(UndergraduateStudent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Database mismatch");
        }
     
    }//GEN-LAST:event_underSubmitbtnActionPerformed

    private void postSubmitbtnpostbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postSubmitbtnpostbtnActionPerformed
       
        
        String nameWithInitials=nameWithInitialstxt.getText();
        String userName=userNametxt.getText();
        String regNo=regNotxt.getText();
        String indexNo=indexNotxt.getText();
        String email=emailtxt.getText();
        String mobile=mobiletxt.getText();
        String nic=admissionDatetxt.getText();
        String address=addresstxt.getText();
        String addmissionDate=admissionDatetxt.getText();
        String institute=insitutetxt.getText();
        String qualificationType=qualificationTypetxt.getText();
        String qualification=qualificationtxt.getText();
        String faculty=facultyIdtxt.getText();
        String courseId=courseIdtxt.getText();
        String password=passwordtxt.getText();
        
       PostgraduateStudentModel postgraduateStudentModel=new PostgraduateStudentModel(nameWithInitials, userName, regNo, indexNo, addmissionDate, email, mobile, nic, address, institute, qualificationType, qualification, faculty, courseId, password);
       
       //int res;
       int res = 0;
        try {
            res = PostgraduateController.addPostStudent(postgraduateStudentModel);
            if(res>0){
           JOptionPane.showMessageDialog(this, "Added Success");
       }
        } 
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
     
    }//GEN-LAST:event_postSubmitbtnpostbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address1txt;
    private javax.swing.JTextArea addresstxt;
    private javax.swing.JTextField admissionDate1txt;
    private javax.swing.JTextField admissionDatetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton cancelpostbtn;
    private javax.swing.JTextField courseIdtxt;
    private javax.swing.JTextField courseIdtxt1;
    private javax.swing.JTextField email1txt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField engGradetxt;
    private javax.swing.JTextField facultyIdtxt;
    private javax.swing.JTextField facultyIdtxt1;
    private javax.swing.JTextField indexNo1txt;
    private javax.swing.JTextField indexNotxt;
    private javax.swing.JTextField insitutetxt;
    private javax.swing.JTextField inslandRanktxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mobile1txt;
    private javax.swing.JTextField mobiletxt;
    private javax.swing.JTextField nameWithInitials1txt;
    private javax.swing.JTextField nameWithInitialstxt;
    private javax.swing.JTextField nic1txt1;
    private javax.swing.JTextField nictxt1;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JPasswordField passwordtxt1;
    private javax.swing.JButton postSubmitbtnpostbtn;
    private javax.swing.JTextField qualificationTypetxt;
    private javax.swing.JTextField qualificationtxt;
    private javax.swing.JTextField regNo1txt;
    private javax.swing.JTextField regNotxt;
    private javax.swing.JTextField subGrade1txt;
    private javax.swing.JTextField subGrade2txt;
    private javax.swing.JTextField subGrade3txt;
    private javax.swing.JTextField subName1txt;
    private javax.swing.JTextField subName2txt;
    private javax.swing.JTextField subName3txt;
    private javax.swing.JButton underSubmitbtn;
    private javax.swing.JTextField userName1txt;
    private javax.swing.JTextField userNametxt;
    private javax.swing.JTextField zScoretxt;
    // End of variables declaration//GEN-END:variables

   /* private void newS_id(){
        String newS_id=IDGenerator.getNewId(tableName, columnName, prefix)
    }*/
}
