/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.SubjectController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.SubjectModel;

/**
 *
 * @author manji
 */
public class Subject extends javax.swing.JFrame {

    public Subject() {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
    }

   /* Subject(){
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    /**
     * @return the backbtn
     */
    public javax.swing.JButton getBackbtn() {
        return backbtn;
    }

    /**
     * @return the cancelbtn
     */
    public javax.swing.JButton getCancelbtn() {
        return cancelbtn;
    }

    /**
     * @return the instroucter1txt
     */
    public javax.swing.JTextField getInstroucter1txt() {
        return instroucter1txt;
    }

    /**
     * @return the instroucter2txt
     */
    public javax.swing.JTextField getInstroucter2txt() {
        return instroucter2txt;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @return the jLabel10
     */
    public javax.swing.JLabel getjLabel10() {
        return jLabel10;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3() {
        return jLabel3;
    }

    /**
     * @return the jLabel4
     */
    public javax.swing.JLabel getjLabel4() {
        return jLabel4;
    }

    /**
     * @return the jLabel5
     */
    public javax.swing.JLabel getjLabel5() {
        return jLabel5;
    }

    /**
     * @return the jLabel7
     */
    public javax.swing.JLabel getjLabel7() {
        return jLabel7;
    }

    /**
     * @return the jLabel9
     */
    public javax.swing.JLabel getjLabel9() {
        return jLabel9;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @return the jPanel6
     */
    public javax.swing.JPanel getjPanel6() {
        return jPanel6;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @return the numberOfAssignmenttxt
     */
    public javax.swing.JTextField getNumberOfAssignmenttxt() {
        return numberOfAssignmenttxt;
    }

    /**
     * @return the numberOfCredittxt
     */
    public javax.swing.JTextField getNumberOfCredittxt() {
        return numberOfCredittxt;
    }

    /**
     * @return the subjectCodetxt
     */
    public javax.swing.JTextField getSubjectCodetxt() {
        return subjectCodetxt;
    }

    /**
     * @return the subjectNametxt
     */
    public javax.swing.JTextField getSubjectNametxt() {
        return subjectNametxt;
    }

    /**
     * @return the submitbtn
     */
    public javax.swing.JButton getSubmitbtn() {
        return submitbtn;
    }

    /**
     * @return the supervisertxt
     */
    public javax.swing.JTextField getSupervisertxt() {
        return supervisertxt;
    }

    /**
     * Creates new form studentReg
     */
    public Subject(String subjectcode, String subjectName, String superviser, String instroucter1, String instroucter2, int numberofcredit, int numberofassignment) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numberOfCredittxt = new javax.swing.JTextField();
        subjectNametxt = new javax.swing.JTextField();
        subjectCodetxt = new javax.swing.JTextField();
        supervisertxt = new javax.swing.JTextField();
        instroucter1txt = new javax.swing.JTextField();
        instroucter2txt = new javax.swing.JTextField();
        submitbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        numberOfAssignmenttxt = new javax.swing.JTextField();
        cancelbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        deletebtn1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(58, 181, 74));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(141, 199, 63));

        jPanel7.setBackground(new java.awt.Color(141, 199, 63));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subject Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(25, 88, 157))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Subject Name");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 47, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Subject Code");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Superviser");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Instroucters 2");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Number of Credit");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        jPanel7.add(numberOfCredittxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

        subjectNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectNametxtActionPerformed(evt);
            }
        });
        jPanel7.add(subjectNametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, -1));

        subjectCodetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCodetxtActionPerformed(evt);
            }
        });
        jPanel7.add(subjectCodetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 100, -1));
        jPanel7.add(supervisertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, -1));
        jPanel7.add(instroucter1txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, -1));
        jPanel7.add(instroucter2txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 100, -1));

        submitbtn.setBackground(new java.awt.Color(49, 144, 176));
        submitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submitbtn.setText("Submit");
        submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtnActionPerformed(evt);
            }
        });
        jPanel7.add(submitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 100, -1));

        backbtn.setBackground(new java.awt.Color(49, 144, 176));
        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setText("Back");
        jPanel7.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 100, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Instroucters 1");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Number of Assignment");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        jPanel7.add(numberOfAssignmenttxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 100, -1));

        cancelbtn.setBackground(new java.awt.Color(49, 144, 176));
        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });
        jPanel7.add(cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 100, -1));

        editbtn.setBackground(new java.awt.Color(49, 144, 176));
        editbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel7.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 100, -1));

        searchbtn.setBackground(new java.awt.Color(49, 144, 176));
        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel7.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 100, -1));

        deletebtn1.setBackground(new java.awt.Color(49, 144, 176));
        deletebtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn1.setText("Delete");
        deletebtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtn1ActionPerformed(evt);
            }
        });
        jPanel7.add(deletebtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 100, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 840, 440));

        jPanel5.setBackground(new java.awt.Color(25, 88, 157));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logo_for_dash.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jLabel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 22, 840, 120));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void jLabel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel1KeyPressed

    }//GEN-LAST:event_jLabel1KeyPressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Dashborad dashborad = new Dashborad();
        dashborad.setVisible(true);
            this.dispose();    }//GEN-LAST:event_jLabel1MouseClicked

    private void subjectNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectNametxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_subjectNametxtActionPerformed

    private void submitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtnActionPerformed
       
        String subjectName=subjectNametxt.getText();
        String subjectCode=subjectCodetxt.getText();
        String superviser=supervisertxt.getText();
        String instroucters1=instroucter1txt.getText();
        String instroucters2=instroucter2txt.getText();
        
        int numberOfCredit=Integer.parseInt(numberOfCredittxt.getText());
        int numberOfAssignment=Integer.parseInt(numberOfAssignmenttxt.getText());
        SubjectModel subject=new SubjectModel(subjectName, subjectCode, superviser, instroucters1, instroucters2, numberOfCredit, numberOfAssignment);
        try{
            
            int res=SubjectController.addSubject(subject);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Added Success");
            }          
        }
        catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
        
    }//GEN-LAST:event_submitbtnActionPerformed
    
    
    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        String subjectCode=subjectCodetxt.getText();
        String subjectName=subjectNametxt.getText();
        String superviser=supervisertxt.getText();
        String instroucter1=instroucter1txt.getText();
        String instroucter2=instroucter2txt.getText();
        int numberOfCredit=Integer.parseInt(numberOfCredittxt.getText());
        int numberOfAssignment=Integer.parseInt(numberOfAssignmenttxt.getText());
        
        SubjectModel subjectModel=new SubjectModel(subjectName, subjectCode, superviser, instroucter1, instroucter2, numberOfCredit, numberOfAssignment);
        try{
            int res=SubjectController.editSubject(subjectModel);
            if(res>0){
                JOptionPane.showMessageDialog(this, "Update Success");
            }
            else{
                JOptionPane.showMessageDialog(this, "Can't Update");
            }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Subject.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editbtnActionPerformed
    
    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        String subjectCode=subjectCodetxt.getText();
        try{
            SubjectModel subjectModel=SubjectController.searchSubject(subjectCode);
            if(subjectModel != null){
                subjectNametxt.setText(subjectModel.getSubjectName());
                supervisertxt.setText(subjectModel.getSuperviser());
                instroucter1txt.setText(subjectModel.getInstroucters1());
                instroucter2txt.setText(subjectModel.getInstroucters2());
                numberOfCredittxt.setText(Integer.toString(subjectModel.getNumberOfCredit()));
                numberOfAssignmenttxt.setText(Integer.toString(subjectModel.getNumberOfAssignment()));
            }
            else {
                JOptionPane.showMessageDialog(this, "No Such Course ");
            }    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Subject.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Subject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void deletebtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtn1ActionPerformed
        String id=subjectCodetxt.getText();
        try {
            int res = SubjectController.deleteSubject(id);
            if (res > 0) {
                JOptionPane.showMessageDialog(this, "Delete Success ");
            } else {
                JOptionPane.showMessageDialog(this, "Delete Fail ");
            }
        }catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No Driver found");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());

        }
    }//GEN-LAST:event_deletebtn1ActionPerformed

    private void subjectCodetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCodetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCodetxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton deletebtn1;
    private javax.swing.JButton editbtn;
    private javax.swing.JTextField instroucter1txt;
    private javax.swing.JTextField instroucter2txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField numberOfAssignmenttxt;
    private javax.swing.JTextField numberOfCredittxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField subjectCodetxt;
    private javax.swing.JTextField subjectNametxt;
    private javax.swing.JButton submitbtn;
    private javax.swing.JTextField supervisertxt;
    // End of variables declaration//GEN-END:variables

  
}
